version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
  configuration: _config.yml # Points to the correct configuration file
python:
  install:
    - requirements: requirements.txt
