version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: _config.yml
  builder: html # Optional but ensures it builds HTML format

python:
  install:
    - requirements: requirements.txt
